# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020939964c06d6a1fc45c0256c361101fab53640aa4aff3e0acfc15c987bb0f26815672c097b9238c653a475c15f410e8d97c7a9b3ada2cec9eb21be16cd2884

test:
  secret_key_base: 1f32c82dda1618b864c1ab4bff51eb09c4c16984e7068d67d46e049d16f03a6378f54f41700ab27d59bb2259f5ece1f25cd94a8576104d72ca3586c2d9758107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
